"""auto gen user phone number

Revision ID: 396562ef2418
Revises: f4772e2cc5ba
Create Date: 2022-07-27 17:11:25.090725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396562ef2418'
down_revision = 'f4772e2cc5ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
